server:
  port: ${PORT:8080}

logging:
  level:
    org.influxdb: DEBUG

management:
  metrics:
    export:
      influx:
        enabled: true
        uri: http://localhost:8086
        auto-create-db: true
        bucket: adobe_db
        user-name: root
        org: adobe_org
        token: <token_key>

        password: password
    web.server.auto-time-requests: true
  endpoints.web.exposure.include: '*'