server:
  port: ${PORT:2222}

logging:
  level:
    org.influxdb: DEBUG

management:
  metrics:
    export:
      influx:
        enabled: true
        uri: http://localhost:8086
        auto-create-db: true
        bucket: adobe_db
        user-name: root
        org: adobe_org
        token: Kv2JdNx7wtwi8LWgH7cGFdrn_7wSaXa381wDr-to1v67e8wc31MdTwEPpRxIS04NcGBQ_BGUq7d-T97kohBMbQ==
        password: password
    web.server.auto-time-requests: true
  endpoints.web.exposure.include: '*'